# Site settings
title: Impact Through Data
email: Kennyliao22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "kennfucius.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: "kennfucius"

# Build settings
markdown: kramdown
