# Site settings
title: Kenneth Liao
description: Impact Through Data
keywords: Data Science, Social Impact, Blog
author: Kennfucius
baseurl: "kennfucius.github.io" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
